version: '3'
services:
  db:
    container_name: bpatch-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
  web:
    container_name: bpatch-app
    depends_on:
      - 'db'
    build:
      context: .
      dockerfile: Dockerfile
    image: mrabets/webphotos-api
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 3000:3000
    volumes:
      - .:/app