default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432
  pool: <%= ENV['DATABASE_POOL'] || 5 %>

development:
  <<: *default
  database: bomba_patch_development

test:
  <<: *default
  database: bomba_patch_test

production:
  <<: *default
